import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
    palavrasContainer: {
      marginTop: -100,
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      alignItems: 'center',
      gap: 20,
    },
    lettersContainer: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'center',
      alignItems: 'center',
      textAlign: 'center',
      marginTop: 130,
      paddingLeft: 33,
      paddingRight: 33,
      rowGap: 10,
      columnGap: 20,
    },
    cacaContainer: {
      marginTop: 150,
      width: 100,
      height: 100,
    },
    caca: {
      flexWrap: 'wrap',
      flexDirection: 'row',
    },
    letter: {
      justifyContent: 'center',
      alignItems: 'center',
      textAlign: 'center',
      fontWeight: 'bold',
      fontSize: 22,
      width: 15,
    },
    sendLetter: {
      flexDirection: 'row',
      marginTop: 30,
      gap: 20,
      justifyContent: 'center',
    },
    inputLetter: {
      width: 200,
      height: 40,
      paddingLeft: 10, 
      backgroundColor: 'gray',
      color: 'black',
    },
    buttonLetter: {
    },
    container: {
      flex: 1,
      alignItems: 'center',
      justifyContent: 'center',
    },
    imageBackground: {
      flex: 1,
      resizeMode: "cover",
      width: "100%",
    },
      retangulo: {
      position: 'absolute',
      top: 51,
      left: 23,
      bottom: 0,
      right: 23,
      width: '89%',
      height: '100%',
      marginTop: 169,
      marginLeft: -2,
      marginRight: -2,
      borderColor: 'white',
      borderRadius: 7,
      },
      button: {
        width: 79,
        height: 79,
        padding: 15,
        bottom: 120,
        left: 5,
      },
      palavras: {
        fontSize: 18,
        color: 'white',
        fontWeight: 'bold',
      },
      palavrasdois: {
        fontSize: 17,
        color: 'white',
        marginTop: 1,
        marginLeft:  90,
        marginRight: 21,
        fontWeight: 'bold',
      },
      palavrastres: {
        fontSize: 17,
        color: 'white',
        marginTop: 1,
        marginLeft:  90,
        marginRight: 21,
        fontWeight: 'bold',
      },
        chapeu: {
          width: 95,
          height: 95,
          padding: 15,
          top: 286,
          left: 7,
        },
        dica: {
          width: 47,
          height: 67,
          padding: 2,
          top: 190,
          left: 310,
        },
  });

export default styles